//! Backend-neutral formal specification registry for Lambars.

#![forbid(unsafe_code)]
#![warn(missing_docs)]

use std::collections::BTreeSet;

/// Verification category.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum SpecKind {
    /// Cargo/feature/toolchain behavior.
    Build,
    /// Runtime behavior.
    Runtime,
    /// Algebraic or optics law.
    Law,
    /// Compile-fail behavior.
    CompileFail,
    /// Concurrent behavior.
    Concurrency,
    /// Serialization behavior.
    Serialization,
    /// Cross-module integration.
    Integration,
    /// Property/model verification.
    Property,
    /// Fuzzing obligation.
    Fuzz,
    /// Miri obligation.
    Miri,
    /// Sanitizer obligation.
    Sanitizer,
    /// Performance/allocation obligation.
    Performance,
    /// Release/CI obligation.
    Release,
}

/// Reusable proof-shape family.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum PatternKind {
    /// Algebraic law family.
    AlgebraicLaw,
    /// N-1/N/N+1 boundary family.
    BoundaryTriplet,
    /// Variant matrix.
    VariantMatrix,
    /// Exactly-once/drop family.
    ExactlyOnceOrDrop,
    /// Round-trip family.
    RoundTrip,
    /// Panic/poison/error family.
    FailureState,
    /// Iterator family.
    IteratorContract,
    /// Structural-sharing family.
    PersistenceContract,
    /// Compile-diagnostic family.
    CompileDiagnostic,
    /// Concurrent state-machine family.
    ConcurrencyStateMachine,
    /// Map/fold/filter/traverse family.
    Transformation,
    /// Unclassified singleton.
    Singleton,
}

/// Required verifier backend bit-set.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct BackendSet(u8);

impl BackendSet {
    /// Verus.
    pub const VERUS: Self = Self(0b01);
    /// Kani.
    pub const KANI: Self = Self(0b10);
    /// Both backends.
    pub const BOTH: Self = Self(Self::VERUS.0 | Self::KANI.0);

    /// Whether all requested bits are present.
    #[must_use]
    pub const fn contains(self, other: Self) -> bool {
        self.0 & other.0 == other.0
    }
}

/// One canonical production-readiness specification.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct FormalSpec {
    /// Stable ID.
    pub id: &'static str,
    /// Canonical test/proof name.
    pub name: &'static str,
    /// Source catalog file.
    pub catalog_file: &'static str,
    /// Source catalog section.
    pub section: &'static str,
    /// Normative requirement sentence.
    pub requirement: &'static str,
    /// Verification category.
    pub kind: SpecKind,
    /// Reusable proof shape.
    pub pattern: PatternKind,
    /// Mandatory backends.
    pub required_backends: BackendSet,
}

/// Metadata generated by `#[derive(FormalModel)]`.
pub trait FormalModel {
    /// Model name.
    const FORMAL_MODEL_NAME: &'static str;
}

/// Metadata generated by `#[derive(ProofDelegate)]`.
pub trait ProofDelegate {
    /// Delegated target.
    const PROOF_DELEGATE_TARGET: &'static str;
}

include!(concat!(env!("OUT_DIR"), "/formal_catalog.rs"));

/// Returns all canonical specifications.
#[must_use]
pub const fn all_specs() -> &'static [FormalSpec] {
    SPECS
}

/// Looks up a specification by canonical name.
#[must_use]
pub fn find_spec(name: &str) -> Option<&'static FormalSpec> {
    all_specs().iter().find(|spec| spec.name == name)
}

/// One registry integrity failure.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CatalogIssue {
    /// Related spec.
    pub spec_name: Option<&'static str>,
    /// Failure message.
    pub message: &'static str,
}

/// Validates uniqueness and mandatory dual-backend coverage.
#[must_use]
pub fn validate_catalog() -> Vec<CatalogIssue> {
    let mut issues = Vec::new();
    let mut ids = BTreeSet::new();
    let mut names = BTreeSet::new();
    if all_specs().len() != SPEC_COUNT {
        issues.push(CatalogIssue {
            spec_name: None,
            message: "count mismatch",
        });
    }
    for spec in all_specs() {
        if !ids.insert(spec.id) {
            issues.push(CatalogIssue {
                spec_name: Some(spec.name),
                message: "duplicate id",
            });
        }
        if !names.insert(spec.name) {
            issues.push(CatalogIssue {
                spec_name: Some(spec.name),
                message: "duplicate name",
            });
        }
        if !spec.required_backends.contains(BackendSet::BOTH) {
            issues.push(CatalogIssue {
                spec_name: Some(spec.name),
                message: "both backends are required",
            });
        }
        if !is_snake_case_identifier(spec.name) {
            issues.push(CatalogIssue {
                spec_name: Some(spec.name),
                message: "invalid canonical Rust identifier",
            });
        }
    }
    issues
}

fn is_snake_case_identifier(value: &str) -> bool {
    let mut chars = value.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    (first.is_ascii_lowercase() || first == '_')
        && chars.all(|ch| ch.is_ascii_lowercase() || ch.is_ascii_digit() || ch == '_')
}

/// Reusable identity/associativity proof triplet.
#[macro_export]
macro_rules! formal_law_triplet {
    (left_identity = $left:expr, right_identity = $right:expr, associativity = $assoc:expr $(,)?) => {{
        assert!($left, "left identity law failed");
        assert!($right, "right identity law failed");
        assert!($assoc, "associativity law failed");
    }};
}

/// Reusable N-1/N/N+1 boundary proof matrix.
#[macro_export]
macro_rules! formal_boundary_triplet {
    ($boundary:expr, |$n:ident| $body:block $(,)?) => {{
        let boundary = $boundary;
        assert!(boundary > 0);
        for value in [boundary - 1, boundary, boundary + 1] {
            let $n = value;
            $body
        }
    }};
}

/// Reusable two-variant proof matrix.
#[macro_export]
macro_rules! formal_variant_pair {
    ($left:expr, $right:expr, |$variant:ident| $body:block $(,)?) => {{
        let $variant = $left;
        $body
        let $variant = $right;
        $body
    }};
}
